### ISSUE TITLE
Windows compatibility for paths in the tests module

### ISSUE THREAD

**Issue by legaultmarc** [pgxcentre/genipe#11]
I think we will run into path compatibility problem when using:

``` python
        data_filename = resource_filename(
            __name__,
            "data/regression_sim.txt.bz2",
        )
```

in the tests module. We should rewrite those bits to:

``` python
        data_filename = resource_filename(
            __name__,
            os.path.join("data", "regression_sim.txt.bz2"),
        )
```

I am not sure if we were going for Windows compatibility in the first place...

**Comment by lemieuxl** [comment]
The main pipeline does not support Windows, since this operating system is not supported by SHAPEIT (phasing tool).

Nevertheless, we might fix this for a future release in case SHAPEIT releases a Windows version. Also, it might be interesting to support Windows for the companion tools (*e.g.* `imputed-stats`).
