### ISSUE TITLE
Module statsmodels, [... WARNING] interaction term is categorical

### ISSUE THREAD

**Issue by dlippold** [pgxcentre/genipe#43]
After I installed genipe (on a fully updated Fedora 25 system) as described in the documentation and after correcting one error (see below) I executed the test and get an error message.

In detail I did the following as root:

`dnf install python3 python3-devel python3-numpy python3-jinja2 python3-pandas python3-setuptools`

And then I did the following as a user:

`pyvenv $HOME/genipe_pyvenv`
`source $HOME/genipe_pyvenv/bin/activate`
`pip install genipe`
`pip install pyfaidx`
`pip install statsmodels`
`deactivate`

Because of another error message (see ticket #41) I then replaced the character 'd' in line 247 of the file genipe/tools/imputed_stats.py by the character 'f'.

Then I did:

`source $HOME/genipe_pyvenv/bin/activate`
`python`
`import genipe`
`genipe.test()`

After that I get the following warning (and an error message which is described in ticket #42):
>[... WARNING] interaction term is categorical: the last category will be used in the results
>[... WARNING] when using interaction, mixedlm optimization cannot be performed, analysis will be slow

The output of the command `source $HOME/genipe_pyvenv/bin/activate; python --version; deactivate` is: Python 3.5.4

**Comment by lemieuxl** [comment]
These are just normal warnings.

The first warning ("*interaction term is categorical*") means that the model includes an interaction between genotype and environment, where the environment is a categorical variable (*e.g.* sex, treatment, etc.). Since we only return one value for each marker, the results will be returned only for the last category. This is not an issue if the variable has 2 categories (*i.e.* results for `sex=1`), but you might lose information when the variable has more than 2 categories.

The second warning ("*mixedlm optimization cannot be performed*") is because we use an optimization to speed up repeated measurements analysis. This optimization doesn't when using an interaction. The analysis will still work, but will be considerably slower. See the [linear mixed effects model](http://pgxcentre.github.io/genipe/tutorials/tutorial_mixedlm.html) in the documentation for more information about the optimization.

Thank you for using *genipe*!
